[git_status]
ahead = "${count}"
diverged = "${ahead_count}${behind_count}"
behind = "${count}"
deleted = "-"
conflicted = ""
untracked = "?"
stashed = "S"
modified = "M"
staged = '[++\($count\)](green)'
renamed = "R"
